### ISSUE TITLE
Error installing the package with NPM

### ISSUE THREAD

**Issue by JanKups** [keystonejs-contrib/k6-contrib#22]
I'm receiving an error while installing the package with NPM

**Action:**
`npm install @k6-contrib/list-plugins`

**Error:**
```
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name ">=^1.0.0": Tags may not have any characters that encodeURIComponent encodes.
```
Using:
```
"@keystone-6/auth": "^1.0.2",
"@keystone-6/cloudinary": "^1.0.0",
"@keystone-6/core": "^1.0.1",
"@keystone-6/fields-document": "^1.0.0",
```

Could this be due to the core version update 1.0.1.?

**Comment by gautamsi** [comment]
seems like issue with the package.json peer dependency version

**Comment by sladg** [comment]
As workaround, you can do `npm install --legacy-peer-deps` on first run. It will generate package-lock.json and normal `npm install` works fine afterwards.

**Comment by skeary** [comment]
I think this is resolved by my PR https://github.com/keystonejs-contrib/k6-contrib/pull/27.
