### ISSUE TITLE
NPM install breaks

### ISSUE THREAD

**Issue by vonba** [keystonejs-contrib/k6-contrib#23]
I'm unable to install the package @k6-contrib/fields-s3.

Running `npm install @k6-contrib/fields-s3` yields the following error:

```
code EINVALIDTAGNAME
Invalid tag name ">=^1.0.0": Tags may not have any characters that encodeURIComponent encodes.
```

I get the same error installing `@k6-contrib/fields-azure`

npm version 8.1.2

**Comment by gautamsi** [comment]
see https://github.com/keystonejs-contrib/k6-contrib/issues/22#issuecomment-1019232164

**Comment by vonba** [comment]
@gautamsi Thank you for your reply. The package seems to install ok on my machine when adding --legacy-peer-deps, but I'm worried about implications when deploying to an external host. Is it likely you'll be able to fix this issue anytime soon?

**Comment by gautamsi** [comment]
I am currently away but will be able to accept PR, should be simple one.

**Comment by vonba** [comment]
I sadly wouldn't know how to fix this myself

**Comment by vonba** [comment]
The workaround does seem to allow me to build on the external server though, so this solves the issue for me for now.
