### ISSUE TITLE
Filename header error with special characters

### ISSUE THREAD

**Issue by g012** [keystonejs-contrib/k6-contrib#25]
Hello,

Trying to send a file with name "Capture d’écran 2022-02-01 à 14.22.37.png", I get this error:
 ERROR: An error occured while resolving input fields.
  - x.file: Invalid character in header content ["x-amz-meta-x-amz-meta-original-filename"]

The filename should probably be sanitized.
Furthermore, it seems x-amz-meta prefix appears twice ; is this an issue as well ?
Thanks !

**Comment by vonba** [comment]
I am also having this issue! Would love to see this solved, any plan to address this?

**Comment by gautamsi** [comment]
all PRs are welcome, I may not have time in next few weeks :(

**Comment by gautamsi** [comment]
s3 and s3-images packages now do not use this header

**Comment by sfodor** [comment]
The same filename "Capture d’écran 2022-02-01 à 14.22.37" seems to fail with Azure (@k6-contrib/fields-azure package) as well:
`x.file: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.`

**Comment by gautamsi** [comment]
I will take a look and update that package as well.
if you can send PR based on what was changed in s3 side, it will be much faster
