### ISSUE TITLE
Support for read view

### ISSUE THREAD

**Issue by sladg** [keystonejs-contrib/k6-contrib#26]
Currently, in `ui.itemView.fieldMode` option for `read` does not work.
If `read` is used, then there is no link for file displayed, in case `edit` option is used, everything works fine, link is visible together with edit buttons.

I would like to have option to use `read` and display link to the file without the extra buttons.

Sample code to replicate the issue:
```
    attachement: s3mappedField({
      ui: {
        itemView: { fieldMode: 'read' },
      },
    }),
```

Empty UI for `Attachment`
<img width="629" alt="Screenshot 2022-02-12 at 14 34 53" src="https://user-images.githubusercontent.com/26263265/153713530-ef467160-beda-43a0-9151-33b68396ba6b.png">

**Comment by gautamsi** [comment]
fixed by showing disabled buttons for read mode (6.1.1)
