### ISSUE TITLE
Sizes not working 

### ISSUE THREAD

**Issue by jaredcowoCS** [keystonejs-contrib/k6-contrib#31]
Currently, I only need to persist the large file. On the docs it mentions that in order to not generate the small and medium sizes, the value for those need to be set to 0, which is what I am doing. 

Here is a snippet of my code. 

```
export const s3Config: S3ImagesConfig = {
  bucket: process.env.S3_BUCKET as string,
  folder: process.env.S3_PATH,
  s3Options: {
    accessKeyId: process.env.S3_ACCESS_KEY_ID,
    secretAccessKey: process.env.S3_SECRET_ACCESS_KEY,
    region: process.env.S3_REGION,
  },
  sizes: { sm: 0, md: 0 },
  uploadParams() {
    return {
      ACL: "public-read",
    };
  },
};
```

**Comment by gautamsi** [comment]
I am going to check this soon. PR welcome in the mean time.

**Comment by gautamsi** [comment]
with release of 6.1.0 sizes should be working as expected.
