### ISSUE TITLE
fields-azure: Add support for preserve storage config parameter

### ISSUE THREAD

**Issue by sfodor** [keystonejs-contrib/k6-contrib#41]
The `preserve ` storage config parameter already exists in Keystone, see https://keystonejs.com/docs/config/config#storage-images-and-files.
Currently the files are not deleted when they are removed from Keystone's database. It means wasted storage space, and possible unwanted files in azure blob storage.

**Comment by gautamsi** [comment]
this is done, let me know if this worked.

**Comment by sfodor** [comment]
Thanks. It works.
