### ISSUE TITLE
Upgrade to @keystone-next 25

### ISSUE THREAD

**Issue by aaronpowell** [keystonejs-contrib/k6-contrib#9]
https://github.com/keystonejs/keystone/blob/master/packages/keystone/CHANGELOG.md#2500

Came out recently with some breaking changes that we'll need to adapt to. Biggest one is the moving around how types are exported

**Comment by gautamsi** [comment]
See draft PR

**Comment by aaronpowell** [comment]
🤦‍♂️ totally missed that.

Glad I hadn't started work on it myself 😅
